Error
Eg11Overiding2.cs(98,13): error CS1061: 'BaseClass' does not contain a definition for 'NonOverridableFunction' and no
        extension method 'NonOverridableFunction' accepting a first argument of type 'BaseClass' could be found (are you        missing a using directive or an assembly reference?)